// Where a story lives.
//
// Articles used to be article.html?id=<id>: one page that looked its content up
// in the browser. Nothing that builds a link preview runs JavaScript, so a story
// pasted into a group chat showed the paper's name and no headline.
//
// Each article now also exists as stories/<id>.html, written by
// `npm run stories` with its real title, description and image already in the
// markup. This is the single place that knows the shape of that URL.
//
// The catch: publishing is automatic. The shared-editing service commits
// published-content.js by itself, and it cannot run Node, so a story can be live
// for readers before anything has generated its page. Linking to a page that is
// not there yet would be worse than the problem this fixes, so the list below
// records which stories actually have one. Anything not in it keeps the old
// article.html?id= link, which always works.
//
// The list is regenerated by setup/build-stories.mjs. Do not edit it by hand.
window.WL_STORY_PAGES = [
  /* BEGIN GENERATED — setup/build-stories.mjs rewrites this */
  "football-dcsaa-state-title",
  "hopkinson-black-history-assembly",
  "achtmeyer-humanities-chair",
  "science-olympiad-dc-tournament",
  "harris-womens-history-assembly",
  "ice-walkout-february",
  "benefit-concert-one-acts",
  "womens-history-month-clubs",
  "facilities-severe-weather",
  "march-madness-maret",
  "service-clubs-engagement",
  "student-activism-youth-voices",
  "intolerant-politics-science-deadly",
  "trump-stealing-midterms",
  "wuthering-whites-review",
  "gun-ownership-privilege-not-right",
  "dc-spring-activities-bloom",
  "beyond-handbook-maret-dress-code",
  "harry-styles-kiss-all-the-time",
  "marets-favorite-literature",
  "mac-lacrosse-bounce-back",
  "mac-tennis-full-swing",
  "ultimate-frisbee-hidden-gem",
  "student-athlete-pressure",
  "isl-softball-momentum",
  /* END GENERATED */
];

// How to reach a page at the site root from wherever we currently are.
//
// Story pages live one directory down, and every link built at runtime —
// the section nav, the search icon, byline links, the editor dashboard — is
// written relative to the root. From stories/ those resolve to
// stories/news.html and so on, which do not exist. The whole nav 404s.
//
// The generated pages already get their <link> and <script> paths rewritten at
// build time, but runtime-generated links are not in the markup to rewrite, so
// they need this instead.
window.WL_rootHref = function (path) {
  var p = String(path == null ? "" : path);
  // Leave anything already absolute, anchored, or a scheme alone.
  if (/^(https?:|data:|mailto:|tel:|javascript:|#|\/)/.test(p)) return p;
  return (/\/stories\//.test(location.pathname) ? "../" : "") + p;
};

window.WL_storyHref = function (id) {
  var slug = String(id == null ? "" : id);
  var hasPage = (window.WL_STORY_PAGES || []).indexOf(slug) !== -1;
  // Paths are relative, so a page already inside stories/ must not nest again.
  var inStories = /\/stories\//.test(location.pathname);

  if (!hasPage) {
    return (inStories ? "../" : "") + "article.html?id=" + encodeURIComponent(slug);
  }
  return (inStories ? "" : "stories/") + encodeURIComponent(slug) + ".html";
};
